export const GENDERS_LIST = ['OTHER', 'TRANSWOMAN', 'TRANSMAN', 'NOGENDER', 'WOMAN', 'MAN']

export const ORIENTATIONS_LIST = ['HETEROSEXUAL', 'HOMOSEXUAL', 'BISEXUAL', 'PANSEXUAL', 'ASEXUAL',
  'SAPIOSEXUAL', 'HETEROFLEXIBLE', 'HOMOFLEXIBLE']
