mutation SectionName($user: UserInput!) {
    updateUser(user: $user) {
        username
        age
        birthdate
        city {
            name
            country
        }
    }
}

mutation SectionGender($user: UserInput!) {
    updateUser(user: $user) {
        gender
        orientation
    }
}

mutation SectionPunchline($user: UserInput!) {
    updateUser(user: $user) {
        punchline
    }
}

mutation addPicture($userID: ID!, $newPicture: PictureInput!) {
    addPicture(userID: $userID, newPicture: $newPicture) {
        raw
        cropped
    }
}

mutation SectionPictures($user: UserInput!) {
    updateUser(user: $user) {
        pictures {
            raw
            cropped
        }
        avatar
    }
}

mutation SectionTags($user: UserInput!) {
    updateUser(user: $user) {
        tags {
            label
            color
            icon
        }
    }
}
